name: nazar
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^1.2.0
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.3
  webview_flutter: ^3.0.4
  map_launcher: ^2.3.0+1
  url_launcher: ^6.1.11
  flutter_native_splash: ^2.1.0
  pandabar: ^0.1.2
  device_preview: ^1.1.0
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  dio: ^5.1.2
  cached_network_image: ^3.2.3
  skeletons: ^0.0.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  google_fonts: ^4.0.4
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/downloads/
    - assets/images/top_movies/
    - assets/images/new_movies/
    - assets/images/top_national/
